# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b05d5fe27942457e1c7be0e708c1f8e42838f218e64ea09ed359993fcaaeec092c53664dfee1d45ea2eb0ea4b70b60e4ffcddcb41c6ca971603644c877168b9b

test:
  secret_key_base: 797abd6ff524390c459399aeba5b89323668d039ef1baff0bb1a03712e140eff7d460cfb035b55a179c4c3cf85c1a1cb299b712192d53bc7a113728c3a6aa6d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
